openapi: 3.0.0
info:
  title: RAG Pipeline API
  description: API for the Retrieval-Augmented Generation pipeline that leverages robotics book content
  version: 1.0.0

paths:
  /ask:
    post:
      summary: Ask a question to the RAG system
      description: Submit a query to the RAG system which retrieves relevant information and generates an answer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response with answer and sources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    QueryRequest:
      type: object
      properties:
        query:
          type: string
          description: The user's question
          example: "What is ROS 2 and how does it work?"
        top_k:
          type: integer
          description: Number of results to retrieve (default 5)
          default: 5
          minimum: 1
          maximum: 20
      required:
        - query

    QueryResponse:
      type: object
      properties:
        query:
          type: string
          description: The original user query
        answer:
          type: string
          description: The generated answer based on retrieved context
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
        retrieved_chunks:
          type: array
          items:
            $ref: '#/components/schemas/RetrievedChunk'
        context_length:
          type: integer
          description: Length of the context used for generation

    RetrievedChunk:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the chunk
        text:
          type: string
          description: The text content of the chunk
        source_file:
          type: string
          description: The source document
        score:
          type: number
          format: float
          description: Relevance score from semantic search

    Source:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the source
        file:
          type: string
          description: Source file name
        relevance:
          type: number
          format: float
          description: Relevance score

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code